Repository fourkitchens/aerate, pull requests merged in 2018-04, with the labels that each got.

#17 Rename to Aerate
  .gitignore
  README.md
  gulpfile.js
  index.js
  mapper/aeratemap/css/build/style.css
  mapper/aeratemap/css/dev/_vars.css
  mapper/aeratemap/css/dev/style.css
  mapper/aeratemap/images/backgrounds/aerate-circle-pattern.png
  mapper/aeratemap/images/backgrounds/aerate-pattern.png
  mapper/aeratemap/images/backgrounds/hatch-sift-pattern.png
  mapper/aeratemap/images/icons/beenhere.svg
  mapper/aeratemap/images/icons/check_box.svg
  mapper/aeratemap/images/icons/check_circle.svg
  mapper/aeratemap/images/icons/control_point.svg
  mapper/aeratemap/images/icons/format_list_bulleted.svg
  mapper/aeratemap/images/icons/format_list_numbered.svg
  mapper/aeratemap/images/icons/info.svg
  mapper/aeratemap/images/icons/people.svg
  mapper/aeratemap/images/icons/person_pin_circle.svg
  mapper/aeratemap/images/icons/pie_chart.svg
  mapper/aeratemap/images/icons/playlist_add.svg
  mapper/aeratemap/images/icons/playlist_add_check.svg
  mapper/aeratemap/images/icons/public.svg
  mapper/aeratemap/images/icons/remove_circle.svg
  mapper/aeratemap/images/icons/report.svg
  mapper/aeratemap/images/icons/stars.svg
  mapper/aeratemap/images/icons/timeline.svg
  mapper/aeratemap/images/logo/aerate-logo.svg
  mapper/aeratemap/index.js
  mapper/aeratemap/js/chart.js
  mapper/aeratemap/js/menu.js
  mapper/aeratemap/template.html
  package-lock.json
  package.json
  scripts/aerate-map.sh
  scripts/sift-map.sh
  wpt.js
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review

#16 Aerate UI branding, part 2
  index.js
  mapper/aeratemap/css/build/style.css
  mapper/aeratemap/css/dev/_menu.css
  mapper/aeratemap/css/dev/_vars.css
  mapper/aeratemap/css/dev/style.css
  mapper/aeratemap/images/fk-logo-reversed.svg
  mapper/aeratemap/js/menu.js
  mapper/aeratemap/template.html
  package-lock.json
  package.json
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review, Type: Enhancement

#22 Github related items and code of conduct
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
Labels: Status: Review Needed

#11 Prettier & ESLint
  .eslintrc.js
  .eslintrc.yml
  gulpfile.js
  index.js
  mapper/aeratemap/index.js
  mapper/aeratemap/js/chart.js
  mapper/aeratemap/js/menu.js
  package-lock.json
  package.json
  prettier.config.js
  src/templates.js
  wpt.js
  yarn-error.log
  yarn.lock
Labels: Status: Passes code review, Status: Passes functional review

#23 console logging fix
  wpt.js
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review, Status: Shipit
